/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chalaka
 */
public class CustomerDetailJFrame extends javax.swing.JFrame {

   private  Customer customer;
   private DBOperation dbops=null;
   private int regNo;
   private String item;
   private String date;
   private int quntity;
   private String payumentMethod;
    public CustomerDetailJFrame(Customer customer) {
        initComponents();
        this.customer=customer;
        this.oldRecordFiller();
        dbops=new DBOperation();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.checkCustomer(customer);
        /********************************************************************/
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pizza", "root", "");
            PreparedStatement st = con.prepareStatement("select *from orders WHERE regular_phone_no=?");
                st.setString(1, customer.getRegulerPhoneNumber()+"");
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            ResultSet rs = st.executeQuery();
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(5);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(500);
            Date d;
            int no;  
            String order, pay_m;
            while (rs.next()){
            
                d = rs.getDate("date");
                no = rs.getInt("order_no");
                order = rs.getString("pizza_beverage_dessert_type");
                pay_m = rs.getString("payment_method");
                model.addRow(new Object[]{d,no,order,pay_m});
            
            }
            
        }catch(Exception e){
        System.out.println(e);
        }

        
        /*******************************************************************/
    }


    private void oldRecordFiller(){
        textTitle.setText               (customer.getTitle());
        textName. setText               (customer.getName());
        textRegularphoneNumber.setText  (Integer.toString(customer.getCallingNumber()));
        textCallingNumber.setText       (Integer.toString(customer.getCallingNumber()));
        textStreet.setText              (customer.getStreet());
        textCrossRoad.setText           (customer.getCrossroad());
        textLandMark.setText            (customer.getLandmark());
        textBlockHouseNumber.setText    (customer.getBlockOrHouseNumber());
        if(customer.getBadge()==null){
            comboBadge.setSelectedItem      (4);
        }else{
        comboBadge.setSelectedItem      (customer.getBadge());
        }
    }
    private void checkCustomer(Customer customer){
        
        if(0==customer.getRegulerPhoneNumber()){
            buttonUpdate.setEnabled(false);
            buttonAdd.setEnabled(true);
        }else{
            buttonAdd.setEnabled(false); 
            buttonUpdate.setEnabled(true);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textRegularphoneNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textCallingNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBadge = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textStreet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        textCrossRoad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textLandMark = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textBlockHouseNumber = new javax.swing.JTextField();
        buttonUpdate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        buttonNext = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Title(Mr,Miss,Ms,Dr)");

        textTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTitleActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jLabel3.setText("Regular phone number");

        textRegularphoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textRegularphoneNumberActionPerformed(evt);
            }
        });

        jLabel4.setText("Calling Number");

        jLabel5.setText("Badge");

        comboBadge.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gold", "Silver", "Platinum", "Do not have" }));
        comboBadge.setToolTipText("");
        comboBadge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBadgeActionPerformed(evt);
            }
        });

        jLabel6.setText("ADDRESS");

        jLabel7.setText("Street");

        jLabel8.setText("Cross road");

        jLabel9.setText("Land Mark");

        jLabel10.setText("Block/House Number");

        buttonUpdate.setText("UPDATE");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonAdd.setText("ADD");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        buttonNext.setText("NEXT");
        buttonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonNextActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Order number", "Order"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(textRegularphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textCallingNumber)
                                        .addComponent(comboBadge, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(textBlockHouseNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                            .addComponent(textLandMark, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textCrossRoad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textStreet, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(468, 468, 468)
                        .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCrossRoad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textRegularphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLandMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCallingNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textBlockHouseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBadge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTitleActionPerformed

    private void comboBadgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBadgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBadgeActionPerformed

    
    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        customer=new Customer();
        
            customer.setTitle(textTitle.getText());
        
        try{
           customer.setCallingNumber(Integer.parseInt(textCallingNumber.getText()));
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Enter Numbers only!!");
            textCallingNumber.setText("");            
        }
        try{
            customer.setRegulerPhoneNumber(Integer.parseInt(textRegularphoneNumber.getText()));
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Enter Numbers only!!");
            textRegularphoneNumber.setText("");
        }
            customer.setName(textName.getText());
            customer.setBadge(comboBadge.getSelectedItem().toString());
            customer.setStreet(textStreet.getText());
            customer.setCrossroad(textCrossRoad.getText());
            customer.setLandmark(textLandMark.getText());
            customer.setBlockOrHouseNumber(textBlockHouseNumber.getText());
            
            if(dbops.updateCustomer(customer)){
                //JOptionPane.showMessageDialog(this, "UPDATED!!");
            }else{
                JOptionPane.showMessageDialog(this, "UPDATE FAIL!!");
            }
        
        
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        customer=new Customer();
        
            customer.setTitle(textTitle.getText());
        
        try{
           customer.setCallingNumber(Integer.parseInt(textCallingNumber.getText()));
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Enter Numbers only!!");
            textCallingNumber.setText("");            
        }
        try{
            customer.setRegulerPhoneNumber(Integer.parseInt(textRegularphoneNumber.getText()));
        }catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Enter Numbers only!!");
            textRegularphoneNumber.setText("");
        }
            customer.setName(textName.getText());
            customer.setBadge(comboBadge.getSelectedItem().toString());
            customer.setStreet(textStreet.getText());
            customer.setCrossroad(textCrossRoad.getText());
            customer.setLandmark(textLandMark.getText());
            customer.setBlockOrHouseNumber(textBlockHouseNumber.getText());
            
            if(dbops.updateCustomer(customer)){
                JOptionPane.showMessageDialog(this, "ADDED!!");
            }else{
                JOptionPane.showMessageDialog(this, "ADDING FAIL!!");
            }
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonNextActionPerformed
        
        if(!textName.getText().isEmpty()&&!textRegularphoneNumber.getText().isEmpty()
                &&!textCallingNumber.getText().isEmpty()
                &&!textStreet.getText().isEmpty()){
                
            JFrame cd=new new_orderJFrame(customer);
                    cd.setTitle("ORDER");
                    cd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    cd.pack();
                    this.dispose();
                    cd.setVisible(true);
        
        }
        
    }//GEN-LAST:event_buttonNextActionPerformed

    private void textRegularphoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textRegularphoneNumberActionPerformed
        
          int searchNumber;
          try {
           searchNumber=Integer.parseInt( textRegularphoneNumber.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter Numbers only Or wrong number!!");         
            return;
        }
            Customer customer = dbops.loadCustomer(new Customer(),searchNumber);
                
            JFrame cd=new CustomerDetailJFrame(customer);
                    cd.setTitle("Customer Detail");
                    cd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    cd.pack();
                    this.dispose();
                    cd.setVisible(true);
        
    }//GEN-LAST:event_textRegularphoneNumberActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonNext;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox comboBadge;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField textBlockHouseNumber;
    private javax.swing.JTextField textCallingNumber;
    private javax.swing.JTextField textCrossRoad;
    private javax.swing.JTextField textLandMark;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textRegularphoneNumber;
    private javax.swing.JTextField textStreet;
    private javax.swing.JTextField textTitle;
    // End of variables declaration//GEN-END:variables
}
