/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*mysql lines in 389*/
package pizza;


import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pahan
 */
public class new_orderJFrame extends javax.swing.JFrame {

    /**
     * Creates new form new_orderJFrame
     */
    public static String str, str2;
    public static float total = 0;
    public Customer cx;
    private Object DateUtils;
    public new_orderJFrame(Customer cx) {
        initComponents();
        this.cx=cx;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ORDER");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Remarks", "Quantity", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("SEARCH BY ITEM NAME");

        jLabel2.setText("SEARCH BY CODE");

        jLabel1.setText("                                                      ");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("            ");

        jLabel5.setText("TOTAL");

        jButton2.setText("PLACE ORDER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CASH", "VISA/MASTER", "AMEX", "VOUCHER" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setText("CODE MANUAL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("DELETE ENTRY");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(220, 220, 220)
                                        .addComponent(jLabel3))
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int n = 0;
        str2 = jLabel1.getText();
        if(!jTextField1.getText().isEmpty() && (!jTextField2.getText().isEmpty() || !jTextField3.getText().isEmpty()))
        {
            try
            {
            n = Integer.parseInt(jTextField1.getText());
            }catch(NumberFormatException e)
            {
                return;
            }
             
            String price = getfromdb("pizza_types","name",jLabel1.getText(),"price");
            if(price == null)
                price = getfromdb("beverage_types","name",jLabel1.getText(),"price");
            if(price == null)
                price = getfromdb("desert_types","name",jLabel1.getText(),"price");
            
            float p = Float.parseFloat(price);
  
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            float tot = p*n;
                             
                model.addRow(new Object[] { jLabel1.getText(), "", n , tot});
                jLabel1.setText("");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField2.requestFocus();
                
                total+=tot;
                jLabel4.setText(String.format("%.2f",total));
                jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
        }    
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

        String s1 = getfromdb("pizza_types","code",jTextField2.getText(),"name");
        if(s1 == null)
            s1 = getfromdb("beverage_types","code",jTextField2.getText(),"name");
        if(s1 == null)
            s1 = getfromdb("desert_types","code",jTextField2.getText(),"name");
        
        if(s1 == null)
        {    
            JOptionPane.showMessageDialog(null,"Please Enter a Valid Code","No code found!",JOptionPane.WARNING_MESSAGE);
            jTextField2.setText("");
        }
        else
        {
            jLabel1.setText(s1);
            jTextField1.requestFocus();
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        int n = 0;
        str2 = jLabel1.getText();
        if(!jTextField1.getText().isEmpty() && (!jTextField2.getText().isEmpty() || !jTextField3.getText().isEmpty()))
        {
            try
            {
            n = Integer.parseInt(jTextField1.getText());
            }catch(NumberFormatException e)
            {
                return;
            }
             
            String price = getfromdb("pizza_types","name",jLabel1.getText(),"price");
            if(price == null)
                price = getfromdb("beverage_types","name",jLabel1.getText(),"price");
            if(price == null)
                price = getfromdb("desert_types","name",jLabel1.getText(),"price");
            
            float p = Float.parseFloat(price);
  
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            float tot = p*n;
                             
                model.addRow(new Object[] { jLabel1.getText(), "", n , tot});
                jLabel1.setText("");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField2.requestFocus();
                
                total+=tot;
                jLabel4.setText(String.format("%.2f",total));
                jLabel4.setHorizontalAlignment(SwingConstants.RIGHT);
        }    
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String pm = String.valueOf(jComboBox1.getSelectedItem());
        
        Item it;

        Order a = new Order();
        a.setTotal(total);
        a.setPayMethod(pm);
        a.setreg_no(this.cx.getRegulerPhoneNumber());

        for(int i = 0; i<jTable1.getRowCount(); i++)
        {
            it = new Item();
            it.setcode((String) jTable1.getValueAt(i, 0));
            it.setprice((float) jTable1.getValueAt(i, 3));
            it.setquantity((int) jTable1.getValueAt(i, 2));
            it.setremark((String) jTable1.getValueAt(i, 1));
            a.add_to_list(it);
            
        }
        
        
          try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pizza", "root", "");
            PreparedStatement st1, st2;
            
            int i = 0;
            String it_name;
            String order = "";
            Item I;
            int q;
            
            while(i != a.getlist_size())
            {
                I = (Item)a.getItem(i);
                it_name = I.getcode();
                q = I.getquantity();
                //System.out.println("a");
                order = order + it_name + " " + q +",";
                i++;
            }
           /**************************************************************************************/
            /***************************************************************************************/
       
           st1 = con.prepareStatement("SELECT max(order_no) from orders where date IN (select max(date) "
                  + "from orders);");
           st2 = con.prepareStatement("SELECT max(date) from orders;");
            ResultSet rs1 = st1.executeQuery();
            ResultSet rs2 = st2.executeQuery();
            
            int orderNo = 0;
            Date d = a.getdate();
   try{        
            if (rs1.next() && rs2.next()) {
                d = rs2.getDate("max(date)");
                orderNo = rs1.getInt("max(order_no)");
                SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");

                if(!sdf.format(d).equals(sdf.format(a.getdate())))
                { 
                    orderNo = 0;
                }    
            }
            }catch(Exception e){
                System.out.println(e+"  after while"); 
                orderNo++;
            }
           
            orderNo++;
            System.out.println(order+"sgadfjsa");
            if(!order.equals(""))
            {
                    st1 = con.prepareStatement("insert into orders (order_no,pizza_beverage_dessert_type,date,regular_phone_no,total_charge,"
                            + "payment_method) "
                            + "values (?,?,?,?,?,?)");
                    st1.setInt(1,orderNo);
                    st1.setString(2,order);
                    st1.setDate(3,a.getdate());
                    st1.setString(4,Integer.toString(a.getreg_no()));

                    st1.setFloat(5, (float) a.getTotal());
                    st1.setString(6,a.getPayMethod());

                    System.out.println(st1+"state");
                    st1.executeUpdate();
                    
                     JFrame on=new OpenJFrame();
                    on.setTitle("NUMBER SEARCH");   
                    on.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    on.pack();
                    this.dispose();
                    on.setVisible(true); 
            }
        } catch (Exception ex) {

            System.out.println(ex+" in orders");
           
            
        }
           
            
      
            
    
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
      
            String s = getfromdb("pizza_types","name",jTextField3.getText(),"name");
            if(s == null)
                s = getfromdb("desert_types","name",jTextField3.getText(),"name");
            if(s == null)
                s = getfromdb("beverage_types","name",jTextField3.getText(),"name");
                 
        if(s == null)
        {    
            JOptionPane.showMessageDialog(null,"Please Enter a Valid Code","No code found!",JOptionPane.WARNING_MESSAGE);
            jTextField2.setText("");
        }
        else
        {
            jLabel1.setText(s);
            jTextField1.requestFocus();
        }
          
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame cg= new code_guideJFrame();
               cg.setTitle("CODE MANUAL");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i = jTable1.getSelectedRow();
        total = total - (float)jTable1.getValueAt(i, 3);
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         if (jTable1.getSelectedRow() != -1) {
            // remove selected row from the model
            model.removeRow(jTable1.getSelectedRow());
            jLabel4.setText(total+"");
        }
         
    }//GEN-LAST:event_jButton4ActionPerformed

    public static String getfromdb(String table,String col, String where, String need)
    {
        try {

            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/Pizza", "root", "");
            PreparedStatement st = con.prepareStatement("select *from " + table + " where "+ col + " = ?");
            st.setString(1,where);

            //Excuting Query
            ResultSet rs = st.executeQuery();

            if (rs.next()) {
                String s = rs.getString(need);
                return s;
            }
            else 
            {
                return null;
            }

            //Create Exception Handler
        } catch (Exception ex) {

            System.out.println(ex);
            return null;
        }
        
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
