/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author chalaka
 */
public class OpenJFrame extends javax.swing.JFrame {
    private DBOperation dbops=null;
    /**
     * Creates new form OpenJFrame
     */
    public OpenJFrame() {
        initComponents();
        dbops=new DBOperation();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textSearchNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonSearch = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        textSearchNumber.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        textSearchNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSearchNumberActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel1.setText("SEARCH   NUMBER");

        buttonSearch.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });
        buttonSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSearchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(textSearchNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textSearchNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSearchNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSearchNumberActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        
        
            int searchNumber;
          try {
           searchNumber=Integer.parseInt( textSearchNumber.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter Numbers only Or wrong number!!");         
            return;
        }
            Customer customer = dbops.loadCustomer(new Customer(),searchNumber);
                
            JFrame cd=new CustomerDetailJFrame(customer);
                    cd.setTitle("Customer Detail");
                    cd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    cd.pack();
                    this.dispose();
                    cd.setVisible(true);
            
            
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void buttonSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonSearchKeyPressed
           int searchNumber;
          try {
           searchNumber=Integer.parseInt( textSearchNumber.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Enter Numbers only Or wrong number!!");         
            return;
        }
            Customer customer = dbops.loadCustomer(new Customer(),searchNumber);
                
            JFrame cd=new CustomerDetailJFrame(customer);
                    cd.setTitle("Customer Detail");
                    cd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    cd.pack();
                    this.dispose();
                    cd.setVisible(true);
    }//GEN-LAST:event_buttonSearchKeyPressed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textSearchNumber;
    // End of variables declaration//GEN-END:variables
}
